---
apiVersion: v1
kind: Namespace

metadata:
  name: nwns
  labels:
    version: v1
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwapp-config
  namespace: nwns

data:
  db_password: changeit
---
apiVersion: v1
kind: Secret

metadata:
  name: nwapp-secret
  namespace: nwns

data:
  db_password: aGVsbG93b3JsZA==
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: northwinddb-deploy
  namespace: nwns
  labels:
    name: northwinddb
    version: v1

spec: 
  # number of pods
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      name: northwinddb
      version: v1
  template:
    # pod template
    metadata:
      name: northwinddb-pod
      labels:
        name: northwinddb
        version: v1
    spec:
      containers:
      - name: northwinddb-container
        image: garethyeo/mynorthwinddb:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nwapp-secret
              key: db_password
        ports:
        - name: mysql-port
          containerPort: 3306
---
apiVersion: v1
kind: Service

metadata:
  name: northwinddb-svc
  namespace: nwns
  labels:
    name: northwinddb-svc
    version: v1

spec:
  type: ClusterIP
  selector:
    name: northwinddb
    version: v1
  ports:
  - name: http
    port: 3306
    targetPort: mysql-port
